version: "3.8"

services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    command: npm start

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - 4500:4500
    expose: 
      - 4500
    command: npm start
    depends_on:
      - mysql
    networks:
      - vacationet

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "12345678"
      ACCEPT_EULA: "Y"
    networks:
      - vacationet

networks:
  vacationet:
    driver: bridge
# connection string: root@127.0.0.1:3306

