version: "3.7"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - ./sqlScripts.sql:/docker-entrypoint-initdb.d/1.sql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "vacation"
      ACCEPT_EULA: "Y"
    networks:
      - vacationet

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - 4500:4500
    expose:
      - 4500
    command: npm start
    depends_on:
      mysql:
        condition: service_started
    networks:
      - vacationet

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    command: npm start

networks:
  vacationet:
    driver: bridge
# connection string: root@127.0.0.1:3306

