version: "3.7"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - 4500:4500
    expose: 
      - 4500
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345678'

    command: npm start
    depends_on:
      - mysql
    networks:
      - vacationet

  mysql:
    image: mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "12345678"
      ACCEPT_EULA: "Y"
    networks:
      - vacationet

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    command: npm start

networks:
  vacationet:
    driver: bridge
# connection string: root@127.0.0.1:3306

